apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: ambassador
spec:
  containers:
  - image: nginx:alpine
    name: frontend
    command: ["sh", "-c", "while true; do sleep 5; date && curl $SERVICE_NAME:8080 -m 2; done"]
    env:
    - name: SERVICE_NAME
      value: "api-service"
