apiVersion: v1
kind: Pod
metadata:
  name: multiple
spec:
  containers:
  - image: busybox
    name: logger
    args:
    - /bin/sh
    - -c
    - >
      count=0;
      while true;
      do
        echo $count > /tmp/log/count.log;
        let count++;
        sleep 5;
      done
    volumeMounts:
    - name: log-volume
      mountPath: /tmp/log
  volumes:
  - name: log-volume
