---
apiVersion: v1
kind: Namespace
metadata:
  name: server
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp
  name: webapp
  namespace: server
spec:
  containers:
  - image: bitnami/express
    env:
      - name: PORT
        value: "3030"
    name: webapp
    resources: {}
    command: ["sh", "-c", "express app && cd app; npm i && npm start"]
    ports:
    - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: webapp
  name: websvc
  namespace: server
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30500
  selector:
    run: webapp
  type: NodePort
---
