apiVersion: v1
kind: Service
metadata:
  labels:
    run: webapp
  name: websvc
  namespace: server
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30500
  selector:
    run: webapp
  type: NodePort
