---
apiVersion: v1
kind: Namespace
metadata:
  name: path-ingress
---
apiVersion: v1
data:
  default.conf.template: |
    server {
        listen       80;
        server_name  localhost;

        location /menu {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri /menu/index.html;
        }
    }
kind: ConfigMap
metadata:
  name: menu-config
  namespace: path-ingress
---
apiVersion: v1
kind: Pod
metadata:
  name: menu-app
  namespace: path-ingress
  labels:
    run: menu-app
spec:
  initContainers:
  - name: init-con
    image: busybox
    command: ['sh', '-c', 'echo "Menu" > /tmp/content/index.html']
    volumeMounts:
    - name: content
      mountPath: /tmp/content
  containers:
  - image: nginx:alpine
    name: menu-app
    volumeMounts:
    - name: content
      mountPath: /usr/share/nginx/html/menu
    - name: conf
      mountPath: /etc/nginx/templates
  volumes:
  - name: content
    emptyDir: {}
  - name: conf
    configMap:
      name: menu-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: menu-app
  name: menu-svc
  namespace: path-ingress
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: menu-app
  type: ClusterIP
---
apiVersion: v1
data:
  default.conf.template: |
    server {
        listen       80;
        server_name  localhost;

        location /contact {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri /contact/index.html;
        }
    }
kind: ConfigMap
metadata:
  name: contact-config
  namespace: path-ingress
---
apiVersion: v1
kind: Pod
metadata:
  name: contact-app
  namespace: path-ingress
  labels:
    run: contact-app
spec:
  initContainers:
  - name: init-con
    image: busybox
    command: ['sh', '-c', 'echo "Contact" > /tmp/content/index.html']
    volumeMounts:
    - name: content
      mountPath: /tmp/content
  containers:
  - image: nginx:alpine
    name: contact-app
    volumeMounts:
    - name: content
      mountPath: /usr/share/nginx/html/contact
    - name: conf
      mountPath: /etc/nginx/templates
  volumes:
  - name: content
    emptyDir: {}
  - name: conf
    configMap:
      name: contact-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: contact-app
  name: contact-svc
  namespace: path-ingress
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: contact-app
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    helm.sh/chart: ingress-nginx-4.0.15
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: 1.1.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller-service
  namespace: ingress-nginx
spec:
  type: NodePort
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  ports:
    - name: http
      port: 80
      nodePort: 31100
      protocol: TCP
      targetPort: http
      appProtocol: http
    - name: https
      port: 443
      nodePort: 30443
      protocol: TCP
      targetPort: https
      appProtocol: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: info-ingress
  namespace: path-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: path-ingress.info
    http:
      paths:
        - path: /contact
          pathType: Prefix
          backend:
            service:
              name: contact-svc
              port:
                number: 80
