apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: persistent
  name: ckad-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: special
