---
apiVersion: v1
kind: Namespace
metadata:
  name: persistent
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ckad-pv
  namespace: persistent
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /tmp/ckad
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: persistent
  name: ckad-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: special
  volumeName: ckad-pv
