---
apiVersion: v1
kind: Namespace
metadata:
  name: service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader-sa
  namespace: service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: service
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: service
  name: pod-reader-binding
  namespace: service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: pod-reader-sa
  namespace: service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pod-reader
  name: pod-reader
  namespace: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-reader
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pod-reader
    spec:
      serviceAccount: default
      containers:
      - image: bitnami/kubectl
        name: kubectl
        command: ["sh", "-c", "while true; do kubectl get pod; sleep 5; done"]
