apiVersion: v1
kind: Pod
metadata:
  name: logger
  namespace: adapter
spec:
  containers:
  - name: count
    image: busybox
    args:
    - /bin/sh
    - -c
    - >
      while true;
      do
        echo {\"datetime\": \"$(date -u)\"} >> /tmp/log/input.log;
        sleep 10;
      done
    volumeMounts:
    - name: tmplog
      mountPath: /tmp/log
  volumes:
  - name: tmplog
    emptyDir: {}
