---
apiVersion: v1
kind: Namespace
metadata:
  name: adapter
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: adapter
data:
  fluent.conf: |
    <source>
      @type tail
      path /tmp/log/input.log
      <parse>
        @type json
      </parse>
      tag logger.format1
    </source>
    <match logger.format1>
      @type file
      path /tmp/log/output
    </match>
---
apiVersion: v1
kind: Pod
metadata:
  name: logger
  namespace: adapter
spec:
  containers:
  - name: logger
    image: busybox
    args:
    - /bin/sh
    - -c
    - >
      while true;
      do
        echo {\"datetime\": \"$(date -u)\"} >> /tmp/log/input.log;
        sleep 10;
      done
    volumeMounts:
    - name: tmplog
      mountPath: /tmp/log
  volumes:
  - name: tmplog
    emptyDir: {}
