---
apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: v1
data:
  index.html: |
    old
kind: ConfigMap
metadata:
  name: old-index-cm
  namespace: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-web
  name: my-web
  namespace: web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-web
  template:
    metadata:
      labels:
        app: my-web
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: index
          mountPath: /usr/share/nginx/html
      volumes:
      - name: index
        configMap:
          name: old-index-cm
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-web
  name: my-svc
  namespace: web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32100
  selector:
    app: my-web
  type: NodePort