---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: v1
kind: Pod
metadata:
  name: web1
  namespace: backend
  labels:
    type: web1
spec:
  containers:
    - name: web1
      image: nginx:alpine
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: web2
  namespace: backend
  labels:
    type: web2
spec:
  containers:
    - name: web2
      image: nginx:alpine
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: web3
  namespace: backend
  labels:
    type: web3
spec:
  containers:
    - name: web3
      image: nginx:alpine
      ports:
      - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: backend
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
