---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: v1
kind: Pod
metadata:
  name: web1
  namespace: backend
  labels:
    type: web1
spec:
  volumes:
  - name: content
  containers:
    - name: web1
      image: nginx:alpine
      volumeMounts:
      - name: content
        mountPath: /usr/share/nginx/html
      ports:
      - containerPort: 80
  initContainers:
  - name: init-con
    image: busybox
    command: ['sh', '-c', 'echo "web1" > /tmp/content/index.html']
    volumeMounts:
    - name: content
      mountPath: /tmp/content
---
apiVersion: v1
kind: Pod
metadata:
  name: web2
  namespace: backend
  labels:
    type: web2
spec:
  volumes:
  - name: content
  containers:
    - name: web2
      image: nginx:alpine
      volumeMounts:
      - name: content
        mountPath: /usr/share/nginx/html
      ports:
      - containerPort: 80
  initContainers:
  - name: init-con
    image: busybox
    command: ['sh', '-c', 'echo "web2" > /tmp/content/index.html']
    volumeMounts:
    - name: content
      mountPath: /tmp/content
---
apiVersion: v1
kind: Pod
metadata:
  name: web3
  namespace: backend
  labels:
    type: web3
spec:
  volumes:
  - name: content
  containers:
    - name: web3
      image: nginx:alpine
      volumeMounts:
      - name: content
        mountPath: /usr/share/nginx/html
      ports:
      - containerPort: 80
  initContainers:
  - name: init-con
    image: busybox
    command: ['sh', '-c', 'echo "web3" > /tmp/content/index.html']
    volumeMounts:
    - name: content
      mountPath: /tmp/content
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: backend
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
